# Generated by Django 4.0.3 on 2022-03-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_fist_name_author_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
